lr: 0.001
seed: 1
if_cuda: True
gamma: 0.5
log_dir: 'logs'
train_batch: 512
val_batch: 256
test_batch: 256
num_workers: 8
model_name: 'encoder-decoder'
data_filepath: '/home/kevin/neural-state-variables-working/circular_motion'
dataset: 'circular_motion'
lr_schedule: [20, 50, 100, 300]
num_gpus: 1
epochs: 5
